server:
  port: ${PORT:8080}

spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: ms-project
          uri: lb://ms-project
          predicates:
            - Path=/project/**
          filters:
            - AuthenticationFilter

        - id: ms-users
          uri: lb://ms-users
          predicates:
            - Path=/users/**
          filters:
            - AuthenticationFilter

        - id: ms-identity
          uri: lb://ms-identity
          predicates:
            - Path=/auth/**
          filters:
            - AuthenticationFilter

        - id: ms-team
          uri: lb://ms-team
          predicates:
            - Path=/team/**
          filters:
            - AuthenticationFilter

        - id: ms-issue
          uri: lb://ms-issue
          predicates:
            - Path=/issue/**
          filters:
            - AuthenticationFilter

        - id: ms-comment
          uri: lb://ms-comment
          predicates:
            - Path=/comment/**
          filters:
            - AuthenticationFilter

        - id: ms-roadmap
          uri: lb://ms-roadmap
          predicates:
            - Path=/roadmap/**
          filters:
            - AuthenticationFilter

management:
  endpoints:
    web:
      exposure:
        include: '*'

eureka:
  instance:
    hostname: localhost
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceURL:
      defaultZone: http://${EUREKA_SERVER_HOST:localhost}:${EUREKA_SERVER_PORT:8761}/eureka/
  management:
    endpoint:
      gateway:
        enabled: true
    endpoints:
      web:
        exposure:
          include: gateway

#jwt:
#  secret: $2a$12$dQNO.bNyF/E4.NC8ZM/kt.oVU31KSpZNMhTNHDEjvh/2z7zrfkoN6
